In [55]:
import numpy as np

a=np.array( [[1,0,0,0,0,0],
           [0,1,0,0,0,0],
           [-1,0,1,0,0,0],
           [0,-1,0,1,0,0],
           [-1,0,0,0,1,0],
           [0,-1,0,0,0,1],
           [0,0,-1,0,1,0],
           [0,0,0,-1,0,1]] )

print(a.ndim)

#B=np.array([[50],[50],[17.32],[10],[40],[30],[22.68],[20]])
B=np.array([[50],[50],[16],[9.6],[39.32],[31.44],[23.68],[20.89]])

print(B.ndim)
print(B)
#print(np.linalg.inv(B))
print(B.shape)

2
2
[[50.  ]
 [50.  ]
 [16.  ]
 [ 9.6 ]
 [39.32]
 [31.44]
 [23.68]
 [20.89]]
(8, 1)


In [56]:
#P = a*np.linalg.inv(np.transpose(a)*a)*np.transpose(a)
aT = np.transpose(a)
m1=np.matmul(aT,a)
m2=np.linalg.inv(m1)
m3=np.matmul(a,m2)
P=np.matmul(m3,aT)
p=np.matmul(P,B)
np.linalg.lstsq(a,p,rcond='warn')


/tmp/ipykernel_4697/67793016.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(a,p,rcond='warn')


(array([[50.        ],
        [50.        ],
        [65.88      ],
        [59.91666667],
        [89.44      ],
        [81.12333333]]),
 array([1.59744333e-29]),
 6,
 array([1.93185165, 1.93185165, 1.73205081, 1.73205081, 0.51763809,
        0.51763809]))